"""Parametric OpenSCAD generator for board enclosures.

Reads the board's `enclosure:` metadata (PCB outline, mount holes,
ports) and emits a self-contained `.scad` file the user opens in
OpenSCAD. The output is a bottom shell with mounting standoffs and
edge cutouts for every defined port; tunables (wall thickness,
clearance, standoff geometry) live at the top of the file so the
user can dial in fit without re-rendering.

Pure: no I/O, no template lookup -- just text. Tests verify the
emitted code mentions every input dimension and that boards without
an `enclosure:` block raise cleanly.
"""
from __future__ import annotations

from wirestudio.library import BoardEnclosure, BoardPort, Library, MountHole
from wirestudio.model import Design


_HEADER = """\
// Generated by wirestudio for design: {design_id}
// Board: {board_name}
//
// This is a starter shell. Tweak the tunables block below to suit
// your printer + part fit. Re-render in OpenSCAD (F5) to preview.

// === Tunables ===
wall = 2.0;            // wall thickness (mm)
floor = 2.0;           // floor thickness (mm)
clearance = 0.6;       // air gap between PCB edge and inner wall
standoff_h = 4.0;      // PCB sits this far above the floor
standoff_d = 5.0;      // standoff outer diameter
standoff_hole = 2.5;   // through-hole on the standoff (M2.5 clearance)
port_clearance = 0.5;  // extra mm around each port cutout
component_h = {component_h};      // tallest part above the PCB top surface

// === Board geometry (mm, from library) ===
board_l = {board_l};
board_w = {board_w};
board_t = {board_t};

// === Derived ===
inner_l = board_l + 2*clearance;
inner_w = board_w + 2*clearance;
outer_l = inner_l + 2*wall;
outer_w = inner_w + 2*wall;
inner_h = standoff_h + board_t + component_h;
outer_h = floor + inner_h;
"""

_SHELL_AND_STANDOFFS = """\

// === Geometry ===
$fn = 32;

module shell() {{
    difference() {{
        // Outer hull.
        cube([outer_l, outer_w, outer_h]);
        // Inner cavity (open top, removes the lid).
        translate([wall, wall, floor])
            cube([inner_l, inner_w, outer_h]);
{port_cutouts}
    }}
}}

module standoffs() {{
    holes = [
{mount_hole_rows}
    ];
    for (h = holes)
        translate([wall + clearance + h[0], wall + clearance + h[1], floor]) {{
            difference() {{
                cylinder(h = standoff_h, d = standoff_d);
                translate([0, 0, -0.1])
                    cylinder(h = standoff_h + 0.2, d = standoff_hole);
            }}
        }}
}}

// === Assembly ===
shell();
standoffs();
"""


def _port_cutout_lines(ports: list[BoardPort]) -> str:
    """Render each port as an OpenSCAD difference operand. Each cutout
    pierces the appropriate wall and is centred along the wall's axis
    according to the port's offset_mm + width_mm. Vertical centring
    uses the port's height_above_pcb_mm: the cutout's centre lands at
    `floor + standoff_h + board_t + height_above_pcb_mm`.
    """
    if not ports:
        return "        // No ports defined for this board."
    lines: list[str] = []
    for p in ports:
        comment = f"        // {p.kind} on {p.edge}"
        cz = "floor + standoff_h + board_t + " + repr(p.height_above_pcb_mm)
        cx_inner = f"wall + clearance + {p.offset_mm}"
        cy_inner = f"wall + clearance + {p.offset_mm}"
        # Each branch translates so the cutout's near face starts at
        # the OUTER wall and extends inward by (wall + 2) so it pierces
        # cleanly even with the clearance gap.
        if p.edge == "short_a":          # x = 0 wall (USB-side typically)
            lines.append(comment)
            lines.append(
                f"        translate([-1, {cy_inner} - port_clearance, "
                f"{cz} - {p.height_mm}/2 - port_clearance])"
            )
            lines.append(
                f"            cube([wall + 2, {p.width_mm} + 2*port_clearance, "
                f"{p.height_mm} + 2*port_clearance]);"
            )
        elif p.edge == "short_b":        # x = length wall
            lines.append(comment)
            lines.append(
                f"        translate([outer_l - wall - 1, "
                f"{cy_inner} - port_clearance, "
                f"{cz} - {p.height_mm}/2 - port_clearance])"
            )
            lines.append(
                f"            cube([wall + 2, {p.width_mm} + 2*port_clearance, "
                f"{p.height_mm} + 2*port_clearance]);"
            )
        elif p.edge == "long_a":         # y = 0 wall
            lines.append(comment)
            lines.append(
                f"        translate([{cx_inner} - port_clearance, -1, "
                f"{cz} - {p.height_mm}/2 - port_clearance])"
            )
            lines.append(
                f"            cube([{p.width_mm} + 2*port_clearance, wall + 2, "
                f"{p.height_mm} + 2*port_clearance]);"
            )
        elif p.edge == "long_b":         # y = width wall
            lines.append(comment)
            lines.append(
                f"        translate([{cx_inner} - port_clearance, "
                f"outer_w - wall - 1, "
                f"{cz} - {p.height_mm}/2 - port_clearance])"
            )
            lines.append(
                f"            cube([{p.width_mm} + 2*port_clearance, wall + 2, "
                f"{p.height_mm} + 2*port_clearance]);"
            )
        else:
            lines.append(f"        // unknown edge {p.edge!r} for {p.kind}; skipped")
    return "\n".join(lines)


def _mount_hole_rows(holes: list[MountHole]) -> str:
    if not holes:
        return "        // No mount holes; the PCB will need to be glued or clipped."
    return ",\n".join(f"        [{h.x_mm}, {h.y_mm}]" for h in holes)


class EnclosureUnavailable(ValueError):
    """Raised when the design's board lacks `enclosure:` metadata, so
    the parametric generator can't run. Modules that plug into a host
    PCB (ESP-01S, etc.) intentionally skip the block."""


def generate_scad(design: Design, library: Library) -> str:
    """Render an OpenSCAD shell for the design's board.

    Walks the board's enclosure block and emits a bottom shell with
    mounting standoffs + edge cutouts for every port. Tunables (wall
    thickness, clearance, standoff geometry) sit at the top of the
    output as plain OpenSCAD assignments so the user can adjust fit
    without re-rendering from the studio.
    """
    board_lib_id = design.board.library_id
    board = library.board(board_lib_id)
    encl: BoardEnclosure | None = board.enclosure
    if encl is None:
        raise EnclosureUnavailable(
            f"board '{board_lib_id}' has no enclosure metadata; "
            f"the parametric generator can't produce a shell. "
            f"Modules without a clear PCB outline (ESP-01S etc.) are intentional."
        )

    header = _HEADER.format(
        design_id=design.id,
        board_name=board.name,
        component_h=encl.component_height_max_mm,
        board_l=encl.pcb.length_mm,
        board_w=encl.pcb.width_mm,
        board_t=encl.pcb.thickness_mm,
    )
    body = _SHELL_AND_STANDOFFS.format(
        port_cutouts=_port_cutout_lines(encl.ports),
        mount_hole_rows=_mount_hole_rows(encl.mount_holes),
    )
    return header + body
