"""Library coverage matrix: which library entries have a passing example.

Walks every library component + board, cross-references the bundled
examples (`wirestudio/examples/*.json`), and emits a markdown report
with two checkbox tables.

A "passing example" is one that ships in `wirestudio/examples/` -- which
implicitly means it round-trips through `esphome config` against the
pinned ESPHome (the merge gate at `.github/workflows/esphome-config.yml`
fails the PR otherwise). So coverage = referenced in any bundled example.

Components / boards with zero examples are flagged: they're library
entries that have never been exercised end-to-end through real ESPHome.
That's not a bug -- some entries are useful but niche -- but it's worth
seeing the gap.

Usage:
    python scripts/coverage_matrix.py                  # write docs/library-coverage.md
    python scripts/coverage_matrix.py --stdout         # print to stdout
    python scripts/coverage_matrix.py --output path.md # write elsewhere

Exit code is always 0 -- this is a reporting tool, not a gate.
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

from wirestudio.library import default_library

REPO_ROOT = Path(__file__).resolve().parent.parent
EXAMPLES_DIR = REPO_ROOT / "wirestudio" / "examples"
DEFAULT_OUTPUT = REPO_ROOT / "docs" / "library-coverage.md"


def _examples_using_component(examples: dict[str, dict]) -> dict[str, list[str]]:
    refs: dict[str, list[str]] = defaultdict(list)
    for ex_id, ex in examples.items():
        for c in ex.get("components") or []:
            lib_id = c.get("library_id")
            if lib_id:
                refs[lib_id].append(ex_id)
    # Stable ordering: alphabetical example ids per component.
    return {k: sorted(set(v)) for k, v in refs.items()}


def _examples_using_board(examples: dict[str, dict]) -> dict[str, list[str]]:
    refs: dict[str, list[str]] = defaultdict(list)
    for ex_id, ex in examples.items():
        board = (ex.get("board") or {}).get("library_id")
        if board:
            refs[board].append(ex_id)
    return {k: sorted(set(v)) for k, v in refs.items()}


def _load_examples() -> dict[str, dict]:
    """Map file-stem -> design dict. The file stem (not the design's
    own ``id`` field) is what the rest of the toolchain uses to refer
    to examples -- ``check_examples.py garage-motion`` finds
    ``garage-motion.json`` regardless of its inner id, and the README
    examples table links by stem too. So the matrix matches that."""
    out: dict[str, dict] = {}
    for path in sorted(EXAMPLES_DIR.glob("*.json")):
        try:
            doc = json.loads(path.read_text())
        except json.JSONDecodeError as e:
            print(f"skipping {path.name}: {e}", file=sys.stderr)
            continue
        out[path.stem] = doc
    return out


def _render(library, examples: dict[str, dict]) -> str:
    component_refs = _examples_using_component(examples)
    board_refs = _examples_using_board(examples)

    components = sorted(library.list_components(), key=lambda c: (c.category, c.id))
    boards = sorted(library.list_boards(), key=lambda b: b.id)

    component_total = len(components)
    component_covered = sum(1 for c in components if component_refs.get(c.id))
    board_total = len(boards)
    board_covered = sum(1 for b in boards if board_refs.get(b.id))

    lines: list[str] = []
    lines.append("# Library coverage")
    lines.append("")
    lines.append(
        "Generated by `scripts/coverage_matrix.py`. Each entry's checkbox flips "
        "based on whether at least one bundled example in `wirestudio/examples/` "
        "uses it. Bundled examples are validated against pinned ESPHome by the "
        "[esphome-config gate](../.github/workflows/esphome-config.yml), so a "
        "✅ here means that library entry round-trips end-to-end through real "
        "ESPHome -- not just that the YAML template renders."
    )
    lines.append("")
    lines.append(
        f"**Summary:** components {component_covered}/{component_total} "
        f"({100 * component_covered // component_total}%), "
        f"boards {board_covered}/{board_total} "
        f"({100 * board_covered // board_total}%)."
    )
    lines.append("")

    lines.append("## Components")
    lines.append("")
    lines.append("| | Library id | Category | Examples |")
    lines.append("|---|---|---|---|")
    for c in components:
        refs = component_refs.get(c.id, [])
        check = "✅" if refs else "⬜"
        ex_links = ", ".join(
            f"[`{e}`](../wirestudio/examples/{e}.json)" for e in refs
        ) or "_(none)_"
        lines.append(f"| {check} | `{c.id}` | {c.category} | {ex_links} |")
    lines.append("")

    lines.append("## Boards")
    lines.append("")
    lines.append("| | Library id | Chip | Examples |")
    lines.append("|---|---|---|---|")
    for b in boards:
        refs = board_refs.get(b.id, [])
        check = "✅" if refs else "⬜"
        ex_links = ", ".join(
            f"[`{e}`](../wirestudio/examples/{e}.json)" for e in refs
        ) or "_(none)_"
        chip = getattr(b, "chip_variant", None) or getattr(b, "mcu", "?")
        lines.append(f"| {check} | `{b.id}` | {chip} | {ex_links} |")
    lines.append("")

    uncovered_components = [c.id for c in components if not component_refs.get(c.id)]
    uncovered_boards = [b.id for b in boards if not board_refs.get(b.id)]
    if uncovered_components or uncovered_boards:
        lines.append("## Coverage gaps")
        lines.append("")
        if uncovered_components:
            lines.append(
                f"Components without an example ({len(uncovered_components)}): "
                + ", ".join(f"`{i}`" for i in uncovered_components)
                + "."
            )
            lines.append("")
        if uncovered_boards:
            lines.append(
                f"Boards without an example ({len(uncovered_boards)}): "
                + ", ".join(f"`{i}`" for i in uncovered_boards)
                + "."
            )
            lines.append("")
        lines.append(
            "Adding an example for any of these earns the ✅ on the next "
            "regeneration. The new example also has to pass the "
            "`esphome config` gate."
        )
        lines.append("")

    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--output", type=Path, default=DEFAULT_OUTPUT,
        help=f"output file (default: {DEFAULT_OUTPUT.relative_to(REPO_ROOT)})",
    )
    parser.add_argument(
        "--stdout", action="store_true",
        help="print to stdout instead of writing a file",
    )
    args = parser.parse_args(argv)

    library = default_library()
    examples = _load_examples()
    text = _render(library, examples)

    if args.stdout:
        sys.stdout.write(text)
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text)
        print(f"wrote {args.output.relative_to(REPO_ROOT)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
